# Site wide configuration

title: Petros Pavlou
description: "A collection of Petros Pavlou artistic creations"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //petrospavlou.github.io/skinny-bones-jekyll

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Petros Pavlou
  web: http://petrospavlou.com
  email: pavlou.maraki@gmail.com
  twitter: none
  bio: "TODO PP bio"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus:
    ad-client:
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
